name: Build Qv2rayBase Shared Library

on:
  push:
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
    name: '${{ matrix.config.name }} S:${{ matrix.FEAT_subscriptions }} L:${{ matrix.FEAT_latency }} STAT:${{ matrix.FEAT_statistics }}' 
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        FEAT_subscriptions: [ON, OFF]
        FEAT_latency: [ON, OFF]
        FEAT_statistics: [ON, OFF]
        config:
        - {
            name: "Windows MSVC", artifact: "Windows-MSVC",
            os: windows-latest,
            cc: "cl.exe", cxx: "cl.exe",
            arch: "win64_msvc2019_64",
            has_msvc: true,
            extra_cmake_args: '-DCMAKE_CONFIGURATION_TYPES="Release;Debug"',
            generator: "\"Ninja Multi-Config\"",
          }
        - {
            name: "Windows MinGW", artifact: "Windows-MinGW",
            os: windows-latest,
            cc: "gcc", cxx: "g++",
            arch: "win64_mingw81",
            extra_cmake_args: "-DUSE_MINGW=ON",
            generator: "\"MinGW Makefiles\""
          }
        - {
            name: "Ubuntu", artifact: "Linux",
            os: ubuntu-latest,
            generator: "Ninja"
          }
        - {
            name: "macOS", artifact: "macOS",
            os: macos-latest,
            generator: "Ninja"
          }
 

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Install MSVC compiler
      if: matrix.config.has_msvc
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.13.2
      with:
        version: 6.2.0
        arch: ${{ matrix.config.arch }}

    - name: Build
      run: |
        mkdir build; cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_INSTALL_PREFIX=installed \
          -DQVFEATURE_subscriptions=${{ matrix.FEAT_subscriptions }} \
          -DQVFEATURE_latency=${{ matrix.FEAT_latency }} \
          -DQVFEATURE_statistics=${{ matrix.FEAT_statistics }} \
          -G${{ matrix.config.generator }} \
          ${{ matrix.config.extra_cmake_args }}
        cmake --build . --config Release --parallel

    - name: Extra build step for MSVC
      if: matrix.config.has_msvc
      run: |
        cd build
        cmake --build . --config Debug --parallel
        cmake --install . --config Debug

    - name: Install
      run: |
        cd build
        cmake --install . --config Release

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Qv2rayBase-${{ matrix.config.artifact }}-S:${{ matrix.FEAT_subscriptions }}-L:${{ matrix.FEAT_latency }}-STAT:${{ matrix.FEAT_statistics }}
        path: build/installed
