
name: Build for Android Platform

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x86_64, armv7, arm64_v8a]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 6.1.0
        target: android
        arch: android_${{ matrix.arch }}

    - name: Install Qt Host
      uses: jurplel/install-qt-action@v2
      with:
        version: 6.1.0
        target: desktop
        set-env: false

    - name: Build
      run: |
        sed -i "s,/home/qt/work/install,/home/runner/work/Qv2rayBase/Qt/6.1.0/gcc_64,g" $Qt6_DIR/lib/cmake/Qt6/qt.toolchain.cmake
        mkdir build; cd build
        $Qt6_DIR/bin/qt-cmake .. -GNinja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=installed \
          -DANDROID_SDK_ROOT=$ANDROID_SDK_ROOT \
          -DANDROID_NDK_ROOT=$ANDROID_NDK_ROOT
        cmake --build . --parallel $(nproc)

    - name: Install
      run: |
        cd build
        cmake --install . --config Release

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Qv2rayBase-Android_${{ matrix.arch }}
        path: build/installed
